extends Node3D

## =============================================================================
## CityBlocking - City Level Controller
## =============================================================================
## City blocking level script - handles player spawn, reset, and kill zone.
## Urban environment level with imported FBX geometry.
##
## Features:
## - Player spawn point for initial position
## - Kill zone for out-of-bounds respawn
## - Auto-generated trimesh collision for imported meshes
##
## Note: Collision is generated by AutoTrimeshCollision component attached
## to SceneCollision node containing the imported FBX.
## =============================================================================

@onready var _player_spawn: Marker3D = $PlayerSpawn
@onready var _player: CharacterBody3D = $PlayerController
@onready var _kill_zone: Area3D = $KillZone

func _ready() -> void:
	# Ensure player starts at spawn position
	if _player and _player_spawn:
		_player.global_position = _player_spawn.global_position
	
	# Connect kill zone signal
	if _kill_zone:
		_kill_zone.body_entered.connect(_on_kill_zone_body_entered)

func _on_kill_zone_body_entered(body: Node3D) -> void:
	if body == _player:
		reset_player_position()

func reset_player_position() -> void:
	if _player and _player_spawn:
		_player.global_position = _player_spawn.global_position
		if _player is CharacterBody3D:
			_player.velocity = Vector3.ZERO
